"""Generate OED reference pages from ``oed.json`` (single source of truth).

The OED standard is defined by ``oed.json`` at the repo root — the same machine-readable
spec that ods-tools consumes. Rather than hand-maintain reference tables, this extension
reads ``oed.json`` at build time and writes MyST Markdown into ``reference/_generated/``
which the reference pages include. Edit ``oed.json`` (and its source CSVs), not the
generated Markdown.

Runs on the Sphinx ``config-inited`` event; also runnable standalone for quick checks.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir, os.pardir))
OED_JSON = os.path.join(REPO_ROOT, "oed.json")
OUT_DIR = os.path.join(HERE, os.pardir, "reference", "_generated")

# input-file groups, in exposure-modelling order
FILE_ORDER = [("Loc", "Location"), ("Acc", "Account"),
              ("ReinsInfo", "Reinsurance Info"), ("ReinsScope", "Reinsurance Scope")]


def _cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").replace("\r", " ").strip()


def _pipe_table(columns, rows):
    out = ["| " + " | ".join(columns) + " |",
           "| " + " | ".join(["---"] * len(columns)) + " |"]
    for row in rows:
        out.append("| " + " | ".join(_cell(c) for c in row) + " |")
    return "\n".join(out)


def _write(name, text):
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8") as fh:
        fh.write(text + "\n")


def generate_fields(oed):
    """input_fields -> field reference, grouped by input file."""
    fields = oed["input_fields"]
    parts = ["<!-- generated by _ext/gen_oed_reference.py from oed.json (input_fields) -->"]
    total = 0
    for key, title in FILE_ORDER:
        recs = fields.get(key)
        if not recs:
            continue
        parts.append(f"\n## {title} (`{key}`)\n")
        rows = []
        for rec in recs.values():
            rows.append([
                rec.get("Input Field Name", ""),
                rec.get("Type & Description", ""),
                rec.get("Data Type", ""),
                rec.get("Property field status", ""),
                rec.get("Default", ""),
            ])
            total += 1
        parts.append(_pipe_table(
            ["Field", "Description", "Data type", "Status", "Default"], rows))
    _write("oed_fields.md", "\n".join(parts))
    return total


def generate_values(oed):
    """Coded value lists -> code reference tables."""
    parts = ["<!-- generated by _ext/gen_oed_reference.py from oed.json (value lists) -->"]
    total = 0

    # perils: nested under 'info'
    perils = oed.get("perils", {}).get("info", {})
    if perils:
        parts.append("\n## Perils\n")
        rows = [[code, r.get("DB table PerilCode", ""), r.get("Peril Description", ""),
                 r.get("Grouped PerilCode", "")] for code, r in perils.items()]
        parts.append(_pipe_table(["Code", "PerilCode", "Description", "Grouped"], rows))
        total += len(rows)

    def simple(key, title, cols):
        nonlocal total
        v = oed.get(key)
        if not isinstance(v, dict):
            return
        parts.append(f"\n## {title}\n")
        rows = [[code] + [rec.get(c, "") for _, c in cols] for code, rec in v.items()]
        parts.append(_pipe_table(["Code"] + [h for h, _ in cols], rows))
        total += len(rows)

    simple("occupancy", "Occupancy codes",
           [("Name", "Name"), ("Description", "Description"), ("Broad Category", "Broad Category")])
    simple("construction", "Construction codes",
           [("Name", "Name"), ("Description", "Description"), ("Broad Category", "Broad Category")])
    simple("country", "Country codes", [("Name", "Name")])
    simple("CoverageValues", "Coverage types",
           [("CoverageID", "CoverageID"), ("Description", "Description"), ("Type", "Type")])
    _write("oed_values.md", "\n".join(parts))
    return total


def _ensure_oed_json():
    """oed.json is a generated artifact (utils/gen-json.py builds it from the CSVs) and is not
    committed. Generate it if missing so the docs build is self-sufficient in CI."""
    if os.path.exists(OED_JSON):
        return
    import subprocess
    import sys
    gen = os.path.join(REPO_ROOT, "utils", "gen-json.py")
    subprocess.run([sys.executable, gen, "--output-path", OED_JSON], cwd=REPO_ROOT, check=True)


def run(app=None, config=None):
    _ensure_oed_json()
    with open(OED_JSON, encoding="utf-8") as fh:
        oed = json.load(fh)
    n_fields = generate_fields(oed)
    n_values = generate_values(oed)
    msg = f"[gen_oed_reference] wrote {n_fields} fields, {n_values} coded values -> reference/_generated/"
    if app is not None:
        from sphinx.util import logging
        logging.getLogger(__name__).info(msg)
    else:
        print(msg)


def setup(app):
    app.connect("config-inited", run)
    return {"parallel_read_safe": True, "parallel_write_safe": True}


if __name__ == "__main__":
    run()
