name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: build
    env:
      SPEC_PATH_IN: './OpenExposureData/Docs/OpenExposureData_Spec.xlsx'
      SPEC_PATH_OUT: './src/data/OpenExposureData_Spec.json'

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        #python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.cfg.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: bin_package
        path: ${{ github.workspace }}/

    - name: Download Spec
      uses: actions/download-artifact@v3
      with:
        name: extracted_spec
        path: ${{ github.workspace }}/src/data/

    - name: install package
      run: pip install ${{ needs.build.outputs.whl_filename }}

    - name: Install test deps
      run: pip install -r tests/requirements.in
      #run: pip install -r tests/requirements.txt

    - name: Run tests
      run: pytest -v
