name: OpenData Testing

on:
  push:
  workflow_dispatch:
    inputs:
      ods_tools_branch:
        description: "Build ODS tools package for tests: [git ref]"
        required: false

env:
  ods_tools_branch: ${{ github.event_name != 'workflow_dispatch' && 'main' ||  inputs.ods_tools_branch }}

jobs:
  build_spec:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  build_package:
    needs: build_spec
    uses: OasisLMF/ODS_Tools/.github/workflows/build.yml@main
    secrets: inherit
    with:
      oed_spec_json: ${{ needs.build_spec.outputs.spec_filename }}
      ods_branch: ${{ github.event_name != 'workflow_dispatch' && 'main' ||  inputs.ods_tools_branch }}

  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: build_package
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Clone ODS_Tools repo
      uses: actions/checkout@v3
      with:
        repository: Oasislmf/ODS_Tools
        ref: ${{ env.ods_tools_branch }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: bin_package
        path: ${{ github.workspace }}/

    - name: install package
      run: pip install ${{ needs.build_package.outputs.whl_filename }}

    - name: Install test deps
      run: pip install -r tests/requirements.in

    - name: Run tests
      run: pytest -v
