name: Update InputFields History

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Version number [semvar]"
        required: true

  workflow_call:
    inputs:
      version_tag:
        description: "Version number [semvar]"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install click pandas packaging

      - name: Verify Branch
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$BRANCH" != "oed-field-from-version" ]; then
            echo "Not on main branch, exiting."
            exit 1
          fi

      - name: Run Script
        run: python ./utils/gen-oed-fields-history.py --version-number ${{ inputs.version_tag }}

      - name: Setup github user
        run: |
          git config --global user.email ${{ env.GIT_EMAIL }}
          git config --global user.name ${{ env.GIT_USERNAME }}
          git config --global pull.ff only
        env:
          GIT_EMAIL: ${{ secrets.BUILD_GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.BUILD_GIT_USERNAME }}


      - name: Commit history
        run: |
          git add -A OpenExposureData/OEDInputFieldsVersionHistory.csv
          git status
          if [[ ! -z $(git status -s) ]]; then
            git commit -m 'Updated InputFields History, version ${{ inputs.version_tag }}'
            git push
          else
            echo 'No changes detected'
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_GIT_TOKEN }}
